version: "3.9"

services:
  postgres:
    container_name: addendum_postgres
    image: postgres:12.5
    environment:
      POSTGRES_DB: addendum
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data: {}
